spring:
  datasource:
    name: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xiaomissm?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    check-template: true
    prefix: classpath:/templates
    encoding: UTF-8
  banner:
    charset: utf-8

server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: utf-8
