spring:
  datasource:
    name: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xiaomissm?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    check-template: true
    prefix: classpath:/templates
    encoding: UTF-8


server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
